name: portfolio_minor
description: Ryan's portfolio

version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flare_flutter: ^2.0.3
  flutter_staggered_animations: ^0.1.2
  flutter_parallax: ^0.1.2
  fluro: 1.6.3
  http: ^0.12.1
  uuid: 2.0.4
  uri: ^0.11.3+1
  url_launcher: ^5.4.10
  flutter_html: 0.11.1
  provider: ^4.1.3
  json_annotation: 3.0.1
  google_fonts: ^1.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  build_runner: 1.8.0
  json_serializable: ^3.3.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/header.jpg
